services:
  - docker
before_install:
  - docker --version
  - docker-compose --version
script:
  - docker build -t tob123/php-apache:1.0 .
  - docker run -d tob123/php-apache:1.0
after_script:
  - docker images
